{% include (destination / "Makefile").as_posix() %}

build:
	$(MAKE) build-image
	$(MAKE) build-config

build-image:
	docker build --pull -t microservice-{{ name }} -f deploy/Dockerfile .
	docker tag microservice-{{ name }}:latest {{ kubernetes_registry }}/microservice-{{ name }}:{{ version }}
	docker push {{ kubernetes_registry }}/microservice-{{ name }}:{{ version }}

build-config:
	kubectl apply -f deploy/deployment.yaml
	kubectl apply -f deploy/service.yaml

restart:
	kubectl rollout restart --namespace={{ project_name }} deployment/microservice-{{ name }} > /dev/null

logs:
	kubectl logs svc/microservice-{{ name }} --namespace={{ project_name }} --follow --tail 1000
