{% include destination + "/Makefile" ignore missing %}

build:
	docker build --no-cache -t {{ project_name }}_{{ name }} -f deploy/Dockerfile .
	docker tag {{ project_name }}_{{ name }}:latest {{ kubernetes_registry }}/{{ project_name }}_{{ name }}:{{ version }}
	docker push {{ kubernetes_registry }}/{{ project_name }}_{{ name }}:{{ version }}
