{% include (destination / "Makefile").as_posix() %}

build:
	docker build --no-cache -t {{ project_name }}-{{ name }} -f deploy/Dockerfile .
	docker tag {{ project_name }}-{{ name }}:latest {{ kubernetes_registry }}/{{ project_name }}-{{ name }}:{{ version }}
	docker push {{ kubernetes_registry }}/{{ project_name }}-{{ name }}:{{ version }}
